groups:
  - name: service_alerts
    interval: 30s
    rules:
      # Alert when service is down
      - alert: ServiceDown
        expr: service_health_status == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Service {{ $labels.service_name }} is down"
          description: "Service {{ $labels.service_name }} has been unhealthy for more than 1 minute"

      # Alert on high error rate
      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.05
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High error rate detected"
          description: "Error rate is above 5% for the last 5 minutes"

      # Alert on slow response times
      - alert: SlowResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Slow response time detected"
          description: "95th percentile response time is above 1 second"

      # Alert on many active alerts
      - alert: TooManyAlerts
        expr: active_alerts_total > 5
        for: 3m
        labels:
          severity: warning
        annotations:
          summary: "Too many active alerts"
          description: "There are {{ $value }} active alerts in the system"