global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'intelligent-monitoring-platform'

# Load alert rules
rule_files:
  - 'alert_rules.yml'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

# Scrape configurations
scrape_configs:
  # Scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Scrape FastAPI backend
  - job_name: 'backend'
    scrape_interval: 10s
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/metrics'